### PR TITLE
Maven parrallel

### PR DESCRIPTION
**Pull request by eddiewebb**
This is being successfully tested on https://circleci.com/gh/eddiewebb/demo-blueskygreenbuilds/1369

Unfortunately due to limitations in yaml and test splitting, we have to have 3 values for:

- parrallel (true/false)
- "" count (default 1)
- Test maching glob pattern 

The last is clunky, but surefire/failsafe both match on either classes in a ut/it package respectively, or ending in Tests/ITs respectively. 

We can decide if its better to default to which..

### CODE REVIEW

**Comment by marcomorain** [comment]
Would this be neater split into two jobs?

- maven/test
- maven/parallel_test

**Comment by eddiewebb** [comment]
> Would this be neater split into two jobs?
> 
> * maven/test
> * maven/parallel_test

I'm leaning that way too.  I also found that projects with parent poms that include .. <include> in failsafe or surefire config will be appended to our explciti list.  So we actually have to generate a _exclude_ list for each node.

I am finishing up those changes and will update this PR sometime today.

**Comment by eddiewebb** [comment]
Now a 2nd job, passing real builds, https://circleci.com/gh/eddiewebb/demo-blueskygreenbuilds/1412#artifacts/containers/0

It includes the excutor parameter from #89, so that should be merged first.

**Comment by iynere** [comment]
should we make the default # of nodes `CIRCLE_NODE_TOTAL` or sth like that ? @eddiewebb

**Comment by eddiewebb** [comment]
> should we make the default # of nodes `$CIRCLE_NODE_TOTAL` or sth like that ? @eddiewebb

You would be caught in a recursive loop.  

"default" values is what sets 'parallelism' which is where CIRCLE_NODE_TOTAL would come from.

**Comment by iynere** [comment]
oh lol duh i'm reading this backwards, ty @eddiewebb

**Comment by iynere** [comment]
@eddiewebb since your READ THIS note is fairly long & involved & seems important, what do you think about adding a `run` step to the job that just echoes the note out for end users on circle ?

**Comment by eddiewebb** [comment]
> @eddiewebb since your READ THIS note is fairly long & involved & seems important, what do you think about adding a `run` step to the job that just echoes the note out for end users on circle ?

I actually originally had it echo'd, but I decided for just comments at top of step.   (As is it gets big bold white font, where as echo was the dull gray that output gets by default)  And since the cat/grep commands are all silent so it reads pretty just as we see it in the yaml.

screen shot 2018-12-14 at 3 32 50 pm


I was torn about including it at all, the comment was more intended for ORB authors, as to why things are implemented the way they are.  I am hoping the parameter descriptions capture consumer concerns well enough.

If we do want to echo it out I'll have to obsess about the right console escape characters to make it all sorts of groovy colors that get your attention.

I'm honestly good either way.

**Comment by iynere** [comment]
well, you had me @ groovy colors @eddiewebb 

u wanna take a stab @ that ?

**Comment by eddiewebb** [comment]
For your consideration:

We can add some orb-like emojis
screen shot 2018-12-14 at 4 14 44 pm

OR 

Simple coloring
screen shot 2018-12-14 at 4 15 23 pm

**Comment by iynere** [comment]
no emojis !!!! @eddiewebb it will break our jobs 😭 https://circleci.atlassian.net/browse/CIRCLE-14320

**Comment by iynere** [comment]
coloring is safe & effective imo

**Comment by eddiewebb** [comment]
screen shot 2018-12-14 at 7 04 00 pm

**Comment by eddiewebb** [comment]
Dev branch orb is passing my demo build - https://circleci.com/gh/eddiewebb/demo-blueskygreenbuilds/1457#config/containers/0

**Comment by iynere** [comment]
niiiiiiice

**Pull request merged**
