### PR TITLE
Pass extra args to docker build.  Fixes #101

### LINKED ISSUE #101: docker-publish/publish does not pass environment variables.
There is no support.  There should be support.

### PR DESCRIPTION
**Pull request by alexanderkjeldaas**

### CODE REVIEW

**Comment by alexanderkjeldaas** [comment]
Untested

**Comment by iynere** [comment]
@alexanderkjeldaas we don't have this setup to publish on forked PRs yet, but I will merge to staging, which will publish a dev release of the orb, and can you test that dev version then ? the complete orb reference will be in the dev-release circleci job

**Comment by alexanderkjeldaas** [comment]
How do I reference the dev version?

**Comment by iynere** [comment]
@alexanderkjeldaas reference it in a circleci config file. the version can be found here: https://circleci.com/gh/CircleCI-Public/circleci-orbs/792 (`circleci/docker-publish@dev:staging-3e282e98fda542f3fc1f64ea7e4a39a2f6adcc04`). you may need to enable uncertified/development orbs on your CircleCI account (`https://circleci.com/gh/organizations/$YOUR_ORG/settings#security` => 'Allow Uncertified Orbs')

**Pull request merged**
