### PR TITLE
Added required description

### LINKED ISSUE #197: codecov-clojure orb missing description for job

### PR DESCRIPTION
**Pull request by KiranAkadas**
### Checklist

- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### CODE REVIEW

**Comment by KyleTryon** [comment]
Hey thanks 👍 ! Could I bother you to push another dummy commit? It looks like perhaps a flakey portion of the test failed and a new commit should resolve it. If that doesnt fix it we'll take the PR and resolve that separately. Thank you!

**Comment by KiranAkadas** [comment]
Sure

**Comment by KiranAkadas** [comment]
Tried several times,
still get the error in #234 
" Not a valid commit name "

**Comment by KyleTryon** [comment]
We'll resolve this issue on our end. Thank you for contributing!

**Comment by KyleTryon** [comment]
Thank you! Codecov is now controlling their orb: https://circleci.com/orbs/registry/orb/codecov/codecov

**Pull request closed without merging**
