### PR TITLE
Improve Gradle Orb

### PR DESCRIPTION
**Pull request by marcomorain**

### CODE REVIEW

**Comment by iynere** [comment]
looks good ! why you changin' `<<parameters>>` to `<< parameters >>` tho @marcomorain ? 😭

**Comment by iynere** [comment]
maybe it doesn't matter—suppose it's a tradeoff b/w concision & readability—altho i have gravitated towards `<<parameters>>` lately, as complex orbs that use a lot of them can get a bit messy & actually hard-to-read if there are too many `<< parameters >>` strung together (imo)

**Comment by tommybo-entur** [comment]
I was just about to create a pr to publish these things (https://github.com/tommybo-entur/circleci-orbs/commit/e9e8b5cc81ac73a97be748bffb15121d94599179). Anyways, there's an assumption here that people keep their test reports in reports/tests/test. We've got additional reports that we keep in another folder (also in reports/tests/) so maybe create a parameter for the ability to override the report location?

**Comment by iynere** [comment]
that's a good idea @tommybo-entur i'll add that in & get this PR updated 🙏

**Pull request merged**
