### PR TITLE
Adding the option to run steps before checkout, like adding ssh-key

### PR DESCRIPTION
**Pull request by tommybo-entur**
### Checklist

- [x ] All new jobs, commands, executors, parameters have descriptions
- [x ] Examples have been added for any significant new features
- [x ] README has been updated, if necessary

### Motivation, issues

I need to add ssh fingerprint before checkout as I wish to push a tag back to origin

### Description

add parameter <before_checkout> to docker-publish/publish

### CODE REVIEW

**Comment by tommybo-entur** [comment]
Think one of the reviewers need to check why dev-release fails. For subsequent commits I only get a message saying I'm unauthorized to run the main workflow.

**Comment by iynere** [comment]
@tommybo-entur it's fine, that's expected, running the `dev-release` job requires access to our internal API token, which is obviously not provided to forked PRs

thank you for the PR ! we'll merge into staging & then `dev-release` should run fine

**Comment by iynere** [comment]
i actually don't think this PR is necessary tho @tommybo-entur 

you can already do this w/ `pre-steps`:

https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps

**Comment by tommybo-entur** [comment]
Thanks, I realized after creating the PR, but left it open as this would conform more to the life cycle you've established. No worries, though. I'm happy to use pre-steps ;-)

**Pull request closed without merging**
