### PR TITLE
let aws-s3 be able to override credentials => master

### PR DESCRIPTION
**Pull request by iynere**
https://github.com/CircleCI-Public/circleci-orbs/pull/137

### CODE REVIEW

**Comment by iynere** [comment]
@zhuangya can you try the dev version of the orb that was just published as part of the merge to `staging` ?

`circleci/aws-s3@dev:staging-34cceb2`

let us know here if it works for you, & if so, we'll merge this to master to get these changes into production

**Comment by zhuangya** [comment]
it's not working :(

`$HOME/.aws/credentials` file shows:

```
[default]
aws_access_key_id = AWS_ACCESS_KEY_ID_SANDBOX
aws_secret_access_key = AWS_SECRET_ACCESS_KEY_SANDBOX

**Comment by zhuangya** [comment]
also, i think it would be better to set region default env name as `AWS_REGION`, otherwise i have to write both `AWS_REGION` and `AWS_DEFAULT_REGION`

any suggestion?

**Comment by iynere** [comment]
@zhuangya you need to pass an `env_var_name` parameter value, not a string. `env_var_name` values do not have `$`:

https://circleci.com/docs/2.0/reusing-config/#environment-variable-name

**Comment by iynere** [comment]
> also, i think it would be better to set region default env name as `AWS_REGION`, otherwise i have to write both `AWS_REGION` and `AWS_DEFAULT_REGION`

sounds good, feel free to submit a PR !

**Comment by zhuangya** [comment]
> you need to pass an `env_var_name` parameter value

you mean, in the orb's source code, i need to specify `AWS_ACCESS_KEY_ID` as type of `env_var_name`?

that is what i did in the last PR, as you can see at https://github.com/CircleCI-Public/circleci-orbs/pull/138/commits/81ad1bc272f617e0579cbcce37381731241e9c7f#diff-0cdebb8dd570ab1229443d6c97e5ae77R81

or maybe i misunderstood this? is there anything incorrect in this https://github.com/CircleCI-Public/circleci-orbs/pull/138/commits/81ad1bc272f617e0579cbcce37381731241e9c7f#diff-0cdebb8dd570ab1229443d6c97e5ae77R48 example?

**Comment by iynere** [comment]
@zhuangya 

> however if i write config.yml as follow, circleci would raise a build error
> 
> ```aws-access-key-id: $AWS_ACCESS_KEY_ID_SANDBOX
> aws-secret-access-key: $AWS_SECRET_ACCESS_KEY_SANDBOX
> ```
> 
> the build error:
> 
> `Type error for argument aws-access-key-id: expected type: env_var_name, actual value: \"$AWS_ACCESS_KEY_ID_SANDBOX\" (type string)`

you're trying to pass a string (`"$AWS_ACCESS_KEY_ID_SANDBOX"`) but the expected parameter type is an `env_var_name` (`AWS_ACCESS_KEY_ID_SANDBOX`)—see our documentation:

https://circleci.com/docs/2.0/reusing-config/#environment-variable-name

**Comment by zhuangya** [comment]
> you're trying to pass a string (`"$AWS_ACCESS_KEY_ID_SANDBOX"`) but the expected parameter type is an `env_var_name` (`AWS_ACCESS_KEY_ID_SANDBOX`)—see our documentation:

i fully understand this, what confuse me more is:



if i override as

```
...

          aws-access-key-id: AWS_ACCESS_KEY_ID_SANDBOX
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_SANDBOX
...
```

and then,

`$HOME/.aws/credentials` file shows:

```
[default]
aws_access_key_id = AWS_ACCESS_KEY_ID_SANDBOX
aws_secret_access_key = AWS_SECRET_ACCESS_KEY_SANDBOX
```

**Comment by iynere** [comment]
that would indicate that you did not actually store those environment variables in a place where your job had access to them @zhuangya

**Comment by iynere** [comment]
ahh, i think i understand the issue @zhuangya

**Comment by iynere** [comment]
let me push a commit to fix

**Comment by iynere** [comment]
ok should be good now 😄 

@zhuangya can you test with `circleci/aws-s3@dev:staging-400bf4e` 🙏

**Comment by zhuangya** [comment]
awesome! i can confirm that it's working with 0.1.13.

but, if there is `AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY` in container's env this override would not work.

so i'm considering maybe we should unset them first?

**Comment by zhuangya** [comment]
otherwise, use can only set envs like `AWS_ACCESS_KEY_ID_ENV1` and use it explicitly

**Comment by iynere** [comment]
i think it's fine @zhuangya, if those env vars are already set they can just pass different values to the parameter

**Comment by zhuangya** [comment]
> i think it's fine @zhuangya, if those env vars are already set they can just pass different values to the parameter

well...unfortunately, nope

aws cli would always use the credentials in `$HOME/.aws/credentials` **AFTER** the ones in environment.

**Comment by iynere** [comment]
hmmmmmm...... i see what you mean @zhuangya 

that actually sounds like a simple fix, you wanna try submitting a new PR ?

would just need to check if those env vars are set, & if they are, temporarily (for the duration of the job) reassign them to, e.g., blank strings or something

**Comment by zhuangya** [comment]
but i think this should be handled by aws-cli...

**Comment by zhuangya** [comment]
> would just need to check if those env vars are set, & if they are, temporarily (for the duration of the job) reassign them to, e.g., blank strings or something

IMHO, this sounds like the steps in aws-cli orb

**Comment by iynere** [comment]
ya that makes sense to me too @zhuangya 

if you submit a PR here i will take a look https://github.com/circleci-public/aws-cli-orb

**Comment by zhuangya** [comment]
ohh! i did not find aws-cli orb in this repo and i thought it would be
close source (:P)

i'll submit a PR for this maybe in a day or two. :D

BR,

----
Ya Zhuang.

**Pull request merged**
